services:
  - type: web
    name: brain-tumor-detection
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd deployment && gunicorn app:app --bind 0.0.0.0:$PORT --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
